#! /usr/bin/env bash

configPath="$HOME/.config/niri/cfg"

# sanity check; a backup of output.kdl must exist
if [[ ! -f $configPath/output.kdl.bak ]]; then
  echo "config modes are already set!"
  exit 1
fi

# the backup of output.kdl is restored
mv $configPath/output.kdl.bak $configPath/output.kdl

exit 0
