#! /usr/bin/env bash

# the contents of clipboard.txt are saved to a variable
strClipboard=$(cat $HOME/Dropbox/clipboard/clipboard.txt)

# sanity check; if there's no text in the clipboard, we exit
if [[ -z "$strClipboard" ]]; then
  exit 1
fi

# strClipboard is sent to the system clipboard
wl-copy <<< "$strClipboard"

exit 0
