#! /usr/bin/env bash

udevadm monitor --udev --subsystem-match=usb_power_delivery  --subsystem-match=scsi_device | \
while read -r line; do
  case "$line" in
    *"add"*"usb_power_delivery"*) canberra-gtk-play -i power-plug ;;
    *"remove"*"usb_power_delivery"*) canberra-gtk-play -i power-unplug ;;
    *"add"*"scsi_device"*) canberra-gtk-play -i device-added ;;
    *"remove"*"scsi_device"*) canberra-gtk-play -i device-removed ;;
  esac;
done
