#!/bin/bash

pactl set-source-mute @DEFAULT_SOURCE@ toggle

LED_PATH="/sys/class/leds/platform::micmute/brightness"

# Check mic mute state
STATE=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')

if [[ "$STATE" == "yes" ]]; then
  sudo /home/david/.myScripts/set-micmute-led.sh 1
else
  sudo /home/david/.myScripts/set-micmute-led.sh 0
fi

