#! /usr/bin/env bash

FLAKE_PATH="/home/david/.dotfiles"

git -C $FLAKE_PATH add flake* hosts/$(hostname)

if git -C $FLAKE_PATH diff --cached --quiet; then
  echo "Nothing to commit."
else
  if niri msg version >/dev/null 2>&1; then # we skip this if niri is not active
    niri msg action spawn -- kitty lazygit -p $FLAKE_PATH
  fi
  CURRENT_GEN=$(readlink /nix/var/nix/profiles/system | grep -o '[0-9]\+')
  DESCRIPTION=$(gum input --placeholder "rebuild description") || DESCRIPTION=""
  git -C $FLAKE_PATH commit -m "$(hostname)-generation $CURRENT_GEN ($(date +"%Y.%m.%d %H:%M:%S"))" -m "$DESCRIPTION"
fi

# done!
exit 0
