# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5201c213-5f9e-4fa6-9cba-40f5362f5ea5";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B6E3-F873";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5201c213-5f9e-4fa6-9cba-40f5362f5ea5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/home/.snapshots" =
    { device = "/dev/disk/by-uuid/5201c213-5f9e-4fa6-9cba-40f5362f5ea5";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5201c213-5f9e-4fa6-9cba-40f5362f5ea5";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/5201c213-5f9e-4fa6-9cba-40f5362f5ea5";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
