#! /usr/bin/env bash

# we expect to receive the App ID and shell command of the desired app
APP_ID="$1"
APP_CMD="$2"

# we retreieve the Window ID from `niri msg windows` by:
# 1. listing all windows matching the desired App ID, and
# 2. findindg the first associated Window ID
WINDOW_ID=$(niri msg windows | grep -B2 "App ID.*$APP_ID" | grep -m 1 "Window ID" | sed 's/.*Window ID \([0-9]*\).*/\1/')

# if WINDOW_ID is empty, then there's no instance of our desired app; we will launch it
if [ -z "$WINDOW_ID" ]; then
  $APP_CMD &
# otherwise, we focus focus the window
else
  niri msg action focus-window --id $WINDOW_ID
fi

# done!
exit 0
