#! /usr/bin/env bash

cd $HOME

# main
if ! tmux has-session -t ws 2>/dev/null; then
  tmux new-session -d -s ws
fi

# aux
if ! tmux has-session -t aux 2>/dev/null; then
  tmux new-session -d -s aux
fi

# IT
if ! tmux has-session -t IT 2>/dev/null; then
  tmux new-session -d -s IT

  # tmux new-window -t IT -n tlp
  # tmux send-keys -t IT:tlp 'watch -n 60 "tlp-stat -t && tlp-stat -p"' Enter

  tmux new-window -t IT -n jctl
  tmux send-keys -t IT:jctl 'clear && systemctl --failed && echo "" && journalctl -b --priority=3 --no-pager' Enter
fi

# main
if ! tmux has-session -t main 2>/dev/null; then
  tmux new-session -d -s main
fi

tmux send-keys -t main 'clear && fastfetch --logo nixos' Enter

if [[ -t 0 ]]; then
  tmux attach -t main
fi

exit 0
