#! /usr/bin/env bash

FLAKE_PATH="/home/david/.dotfiles"

git -C $FLAKE_PATH add flake* nix

if git -C $FLAKE_PATH diff --cached --quiet; then
  echo "Nothing to commit."
else
  CURRENT_GEN=$(readlink /nix/var/nix/profiles/system | grep -o '[0-9]\+')
  git -C $FLAKE_PATH commit -m "nixos-generation $CURRENT_GEN - $(date +"%Y.%m.%d %H:%M:%S")"
fi

# done!
exit 0
