#! /usr/bin/env bash

# we retreieve the current state of eDP-1 by:
# 1. looking for its entry under `niri msg outputs`
# 2. searching for the "Disabled" state; anything else will mean it is enabled
CURRENT_STATE=$(niri msg outputs | grep -A2 eDP-1 | grep Disabled)

# if `CURRENT_STATE` is empty, then eDP-1 is enabled; it will get disabled
if [ -z "$CURRENT_STATE" ]; then
  niri msg output "eDP-1" off
# otherwise, it will get enabled
else
  niri msg output "eDP-1" on
fi

# done!
exit 0
