# zmodload zsh/zprof # to debug loading time

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install

# Initialize completion system
autoload -Uz compinit
compinit

# >>> aniadir cosas a path >>>
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

export PATH

# >>> init de cosas varias >>>

export STARSHIP_CONFIG="$HOME/.config/starship/config.toml";
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(fzf --zsh)" # Set up fzf key bindings and fuzzy completion

# >>> aliases y preferencias varias >>>
alias zsh-reload='source ~/.zshrc'
alias notes='nvim ~/Projects/my\ wiki/notes.md'
alias clipboard='nvim ~/Dropbox/clipboard/clipboard.txt'
alias cd='z'
alias ls='lsd' # lsd stuff
alias l='ls -l' # lsd stuff
alias la='ls -a' # lsd stuff
alias lla='ls -la' # lsd stuff
alias lt='ls --tree' # lsd stuff
alias fzf="fzf --preview 'bat --style=numbers --color=always {}'"
alias open="xdg-open"
alias db="maestral"
alias tks="tmux kill-server"
alias tat="tmux a -t"
alias fillbat="sudo tlp fullcharge BAT0"
alias pingNixos="ping nixos.org"
alias du="btrfs filesystem du"
alias df="btrfs filesystem usage"
alias nm-restart="sudo systemctl restart NetworkManager"

# nix shells
alias jupyter-shell="nix develop /home/david/.dotfiles#jupyter"
function shell() {
  nix develop /home/david/.dotfiles#"$1"
}

# private stuff
if [ -f "$HOME/.zshrc.private" ]; then
  source "$HOME/.zshrc.private"
else
  echo -e "[\033[33mWARNING:\033[0m] ~/.zshrc.private not found!"
fi

# landing shell
if [[ -n "$PS1" && -z "$TMUX" && -z "$IN_NIX_SHELL" ]]; then # if not in tmux, nor in nix shell
  if [[ -n "$SSH_CONNECTION" ]]; then # if connected through ssh
    $HOME/.local/bin/gentmux
  else
    fastfetch
  fi
fi

# to make yazi exit at cwd
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
