# docs: https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$nix_shell$python$os$hostname$directory$git_branch$character"

# Inserts a blank line between shell prompts
add_newline = false

[nix_shell]
format = '[\($symbol$name\)]($style) '
symbol = ""

[python]
format = '[${pyenv_prefix}](bold yellow)'

[os]
disabled = false
format = '[$symbol](bold purple)'

[hostname]
ssh_only = false
format = '[$hostname](bold purple) '

[directory]
truncation_length = 1
truncation_symbol = "../"
format = '[$path](bold green) '

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)](#d2573f) '

[character]
success_symbol = '[❯](bold yellow)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❯](bold green)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "
