# tip: use `keyd list-keys` to list keys
# tip: use `sudo keyd monitor` to monitor key strokes

#------------------------------------------------------------------------------#
# my settings are applied across all keyboards
[ids]
*
#------------------------------------------------------------------------------#
[main]
# Caps Lock acts as Esc when tapped, and as Ctrl when held
capslock = overload(control,esc)

# Left Alt is swapped with Left Meta
leftmeta = leftalt
leftalt = leftmeta

# Left Ctrl acts as Left Hyper, Copilot acts as Right Hyper
leftcontrol = layer(hyper_L)
f23 = layer(hyper_R)

# ` acts as ` when tapped, and as my Math layer when held
` = overload(Math, `)

# Shift keys are passed to separate layers for configuration
leftshift = layer(shift_L)
rightshift = layer(shift_R)

#------------------------------------------------------------------------------#
# Pressing both Shifts together toggles Caps Lock; otherwise they're just Shift
[shift_L:S]
rightshift = capslock

[shift_R:S]
leftshift = capslock
#------------------------------------------------------------------------------#
# Hyper keys; vim and media keys are hard coded to Left Hyper
[hyper_L:C-S-A-M]
enter = playpause
left = previoussong
right = nextsong
h = left
j = down
k = up
l = right

[hyper_R:C-M]
#------------------------------------------------------------------------------#
# Math layer; Numpad
[Math]
/ = .
n = 0
m = 1
, = 2
. = 3
j = 4
k = 5
l = 6
u = 7
i = 8
o = 9
8 = /
9 = *
0 = -
p = +
; = =
