# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d8c189cf-6c3d-4b14-85d2-32d5602a5819";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A189-0A7A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/c18b130c-eea4-4279-bf37-1cf3b2f0f9d0";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d8c189cf-6c3d-4b14-85d2-32d5602a5819";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/home/.snapshots" =
    { device = "/dev/disk/by-uuid/d8c189cf-6c3d-4b14-85d2-32d5602a5819";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d8c189cf-6c3d-4b14-85d2-32d5602a5819";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/d8c189cf-6c3d-4b14-85d2-32d5602a5819";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
